

BLOCK=16 #한 타일의 가로/세로 길이
SCREEN_WIDTH = 480  #가로 크기
SCREEN_HEIGHT = 640  #세로 크기

TILE_WIDTH=SCREEN_WIDTH//BLOCK #가로 타일 수
TILE_HEIGHT=SCREEN_HEIGHT//BLOCK #세로 타일 수

#보이는 맵의 크기
ON_SCREEN_MAP_WIDTH=SCREEN_WIDTH
ON_SCREEN_MAP_HEIGHT=(SCREEN_HEIGHT//10*9)
